name: Reset Inject State

on:
  workflow_dispatch:

permissions:
  actions: write

jobs:
  reset:
    runs-on: ubuntu-latest
    steps:
      - name: Delete inject-state artifact
        uses: geekyeggo/delete-artifact@v2
        with:
          name: inject-state
